#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d web edit code chat dash music etc

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#344756"
bspc config presel_feedback_color "#595B82"

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Min desktop='^1'
bspc rule -a Chromium desktop='^1'
bspc rule -a neovim desktop='^3'
bspc rule -a org.telegram.desktop desktop='^4'
bspc rule -a com.todoist.Todoist desktop='^5'
# language switch
setxkbmap -option grp:alt_shift_toggle us,ru &

$HOME/.config/polybar/launch.sh
picom
nitrogen --restore
